#ifndef __COMMON_EVENT_EVENT_TYPE_HH__
#define __COMMON_EVENT_EVENT_TYPE_HH__

enum EventType {
	EVENT_TYPE_UNDEFINED,
	EVENT_TYPE_APPLICATION,
	EVENT_TYPE_CODING,
	EVENT_TYPE_COORDINATOR,
	EVENT_TYPE_IO,
	EVENT_TYPE_CLIENT,
	EVENT_TYPE_SERVER,
	EVENT_TYPE_SERVER_PEER,
	EVENT_TYPE_REMAP_MSG,
	EVENT_TYPE_DUMMY
};

#endif
