#ifndef __COMMON_EVENT_EVENT_QUEUE_TYPE_HH__
#define __COMMON_EVENT_EVENT_QUEUE_TYPE_HH__

enum EventQueueType {
	EVENT_QUEUE_TYPE_UNDEFINED,
	EVENT_QUEUE_TYPE_MIXED,
	EVENT_QUEUE_TYPE_SEPARATED
};

#endif
