#ifndef __COMMON_EVENT_EVENT_TYPE_HH__
#define __COMMON_EVENT_EVENT_TYPE_HH__

enum EventType {
	EVENT_TYPE_UNDEFINED,
	EVENT_TYPE_APPLICATION,
	EVENT_TYPE_CODING,
	EVENT_TYPE_COORDINATOR,
	EVENT_TYPE_IO,
	EVENT_TYPE_MASTER,
	EVENT_TYPE_SLAVE,
	EVENT_TYPE_SLAVE_PEER,
	EVENT_TYPE_REMAP_MSG
};

#endif
