#ifndef __COMMON_EVENT_EVENT_TYPE_HH__
#define __COMMON_EVENT_EVENT_TYPE_HH__

enum EventType {
	EVENT_TYPE_UNDEFINED,
	EVENT_TYPE_MIXED,
	EVENT_TYPE_APPLICATION,
	EVENT_TYPE_COORDINATOR,
	EVENT_TYPE_MASTER,
	EVENT_TYPE_SLAVE
};

#endif
